"""
signal_engine.py — Live Signal Engine
Runs strategies on real-time data during market hours.
Generates BUY/SELL/HOLD signals with confidence scores.
Fires Telegram alerts when actionable signals are found.
"""

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional

import pandas as pd
from dotenv import load_dotenv

from data_fetch import get_provider
from strategy import build_strategy, STRATEGY_REGISTRY, BUY, SELL, HOLD

load_dotenv()
logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────────
# Telegram alert (uses python-telegram-bot or requests)
# ──────────────────────────────────────────────────────────────────────────────

def send_telegram_alert(message: str) -> bool:
    """
    Send a Telegram message to the configured chat.

    Setup in .env:
        TELEGRAM_BOT_TOKEN=your_bot_token
        TELEGRAM_CHAT_ID=your_chat_id   # group or personal chat ID

    Returns True if sent successfully.
    """
    import requests

    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    if not token or not chat_id:
        logger.warning(
            "Telegram not configured. Add TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to .env"
        )
        return False

    try:
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": message,
            "parse_mode": "HTML",
            "disable_web_page_preview": True,
        }
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            logger.info("Telegram alert sent successfully")
            return True
        else:
            logger.error(f"Telegram error: {response.status_code} — {response.text}")
            return False
    except Exception as e:
        logger.error(f"Telegram send failed: {e}")
        return False


# ──────────────────────────────────────────────────────────────────────────────
# Signal dataclass
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class Signal:
    """A trading signal generated by the signal engine."""
    symbol: str
    action: str                  # "BUY", "SELL", "HOLD"
    confidence: float            # 0.0 to 1.0
    price: float
    timestamp: datetime
    strategy_votes: dict         # {strategy_name: action}
    reasoning: str               # human-readable explanation
    stop_loss_price: float = 0.0
    take_profit_price: float = 0.0


# ──────────────────────────────────────────────────────────────────────────────
# Signal Engine
# ──────────────────────────────────────────────────────────────────────────────

class SignalEngine:
    """
    Multi-strategy signal engine with confidence scoring.

    How it works:
    1. Fetches recent price data for each symbol
    2. Runs all configured strategies
    3. Aggregates votes → confidence score
    4. Fires alert if confidence exceeds threshold
    5. Sends Telegram notification for actionable signals

    Confidence score = fraction of strategies agreeing on direction.
    Example: 3/3 strategies say BUY → confidence = 1.0 (very high)
             2/3 strategies say BUY → confidence = 0.67 (moderate)
             Mixed → HOLD signal
    """

    def __init__(
        self,
        symbols: list[str],
        strategy_names: Optional[list[str]] = None,
        lookback_days: int = 200,
        alert_threshold: float = 0.6,     # min confidence to fire alert
        stop_loss_pct: float = 5.0,       # stop loss %
        take_profit_pct: float = 10.0,    # take profit target %
    ):
        self.symbols = [s.upper() for s in symbols]
        self.strategy_names = strategy_names or list(STRATEGY_REGISTRY.keys())
        self.lookback_days = lookback_days
        self.alert_threshold = alert_threshold
        self.stop_loss_pct = stop_loss_pct
        self.take_profit_pct = take_profit_pct
        self.provider = get_provider("yfinance")
        self._last_alerts: dict[str, str] = {}  # symbol → last action alerted

    def scan(self, notify: bool = True) -> list[Signal]:
        """
        Run a full scan across all symbols and strategies.

        Args:
            notify: If True, send Telegram alerts for actionable signals

        Returns:
            List of Signal objects for all symbols
        """
        signals = []
        end = datetime.today().strftime("%Y-%m-%d")
        start = (datetime.today() - timedelta(days=self.lookback_days)).strftime("%Y-%m-%d")

        for symbol in self.symbols:
            try:
                signal = self._scan_symbol(symbol, start, end)
                signals.append(signal)

                # Alert only if above threshold and action changed
                if notify and signal.confidence >= self.alert_threshold:
                    if signal.action != "HOLD":
                        last = self._last_alerts.get(symbol)
                        if last != signal.action:
                            self._send_signal_alert(signal)
                            self._last_alerts[symbol] = signal.action

            except Exception as e:
                logger.error(f"Scan failed for {symbol}: {e}")

        return signals

    def _scan_symbol(self, symbol: str, start: str, end: str) -> Signal:
        """Run all strategies on one symbol and aggregate votes."""
        df = self.provider.get_bars(symbol, "1d", start, end)
        current_price = float(df["Close"].iloc[-1])

        votes = {}
        for strategy_name in self.strategy_names:
            try:
                strategy = build_strategy(strategy_name)
                signals_df = strategy.generate_signals(df.copy())
                last_signal = int(signals_df["signal"].iloc[-1])
                if last_signal == BUY:
                    votes[strategy_name] = "BUY"
                elif last_signal == SELL:
                    votes[strategy_name] = "SELL"
                else:
                    votes[strategy_name] = "HOLD"
            except Exception as e:
                logger.warning(f"{strategy_name} failed on {symbol}: {e}")
                votes[strategy_name] = "HOLD"

        # Count votes
        total = len(votes)
        buy_votes = sum(1 for v in votes.values() if v == "BUY")
        sell_votes = sum(1 for v in votes.values() if v == "SELL")

        # Determine action and confidence
        if buy_votes > sell_votes and buy_votes > total / 2:
            action = "BUY"
            confidence = buy_votes / total
        elif sell_votes > buy_votes and sell_votes > total / 2:
            action = "SELL"
            confidence = sell_votes / total
        else:
            action = "HOLD"
            confidence = max(buy_votes, sell_votes) / total if total > 0 else 0.0

        # Risk levels
        stop_loss_price = round(current_price * (1 - self.stop_loss_pct / 100), 4)
        take_profit_price = round(current_price * (1 + self.take_profit_pct / 100), 4)

        # Human reasoning
        reasoning = self._build_reasoning(symbol, action, votes, confidence, current_price)

        return Signal(
            symbol=symbol,
            action=action,
            confidence=round(confidence, 3),
            price=current_price,
            timestamp=datetime.utcnow(),
            strategy_votes=votes,
            reasoning=reasoning,
            stop_loss_price=stop_loss_price,
            take_profit_price=take_profit_price,
        )

    def _build_reasoning(
        self,
        symbol: str,
        action: str,
        votes: dict,
        confidence: float,
        price: float,
    ) -> str:
        """Build a plain-English explanation of the signal."""
        vote_summary = ", ".join([f"{k.split('(')[0].strip()}: {v}" for k, v in votes.items()])
        confidence_label = (
            "Very High" if confidence >= 0.9 else
            "High" if confidence >= 0.7 else
            "Moderate" if confidence >= 0.5 else
            "Low"
        )

        lines = [
            f"{symbol} @ ${price:.2f}",
            f"Signal: {action} | Confidence: {confidence_label} ({confidence:.0%})",
            f"Strategies: {vote_summary}",
        ]

        if action == "BUY":
            lines.append(f"Entry: ${price:.2f} | Stop Loss: ${price * (1 - 0.05):.2f} | Target: ${price * (1 + 0.10):.2f}")
        elif action == "SELL":
            lines.append("Consider closing or reducing your position.")

        return "\n".join(lines)

    def _send_signal_alert(self, signal: Signal):
        """Format and send a Telegram alert for an actionable signal."""
        action_emoji = "🟢" if signal.action == "BUY" else "🔴" if signal.action == "SELL" else "🟡"
        confidence_pct = f"{signal.confidence:.0%}"

        votes_text = "\n".join([
            f"  • {name.split('(')[0].strip()}: {vote}"
            for name, vote in signal.strategy_votes.items()
        ])

        message = f"""
{action_emoji} <b>TRADING SIGNAL — {signal.symbol}</b>

<b>Action:</b> {signal.action}
<b>Price:</b> ${signal.price:,.2f}
<b>Confidence:</b> {confidence_pct}
<b>Time:</b> {signal.timestamp.strftime('%Y-%m-%d %H:%M UTC')}

<b>Strategy Votes:</b>
{votes_text}

<b>Risk Levels:</b>
  🛑 Stop Loss: ${signal.stop_loss_price:,.2f} (-{5}%)
  🎯 Take Profit: ${signal.take_profit_price:,.2f} (+{10}%)

<i>This is a signal, not financial advice. You decide.</i>
""".strip()

        send_telegram_alert(message)
        logger.info(f"Alert sent: {signal.action} {signal.symbol} @ ${signal.price}")


def signals_to_df(signals: list[Signal]) -> pd.DataFrame:
    """Convert signal list to a display-ready DataFrame."""
    rows = []
    for s in signals:
        rows.append({
            "Symbol": s.symbol,
            "Action": s.action,
            "Confidence": f"{s.confidence:.0%}",
            "Price": f"${s.price:,.2f}",
            "Stop Loss": f"${s.stop_loss_price:,.2f}",
            "Take Profit": f"${s.take_profit_price:,.2f}",
            "Time": s.timestamp.strftime("%H:%M UTC"),
            "Votes": " | ".join([f"{k.split('(')[0].strip()}={v}" for k, v in s.strategy_votes.items()]),
        })
    return pd.DataFrame(rows)


if __name__ == "__main__":
    # Quick test — scan a few large-cap stocks
    engine = SignalEngine(
        symbols=["AAPL", "MSFT", "NVDA", "AMZN", "TSLA"],
        alert_threshold=0.6,
    )
    signals = engine.scan(notify=False)  # notify=False skips Telegram in test

    for s in signals:
        print(f"\n{s.symbol}: {s.action} | Confidence: {s.confidence:.0%} | ${s.price:.2f}")
        print(f"  Votes: {s.strategy_votes}")
        print(f"  Stop: ${s.stop_loss_price} | Target: ${s.take_profit_price}")
